telemetry = false

[install]
exact = true
auto = "auto"

[test]
coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = [
    "src/index.ts",
    "src/config.ts"
]
